/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import dao.BoxAtencionDAO;
import dao.GestionesDAO;
import dao.ModeloAtencionDiferenciadaDAO;
import dao.RegistrarAtencionDAO;
import dao.TurneroDAO;
import modelo.Gestiones;
import modelo.RegistrarAtencion;
import modelo.Turnero;
import modelo.Cliente;
import modelo.Colaborador;
import java.time.LocalDate;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author m29ee
 */
public class frmRegistrarAtencion extends javax.swing.JFrame {

    private BoxAtencionDAO boxAtencionDAO;
    private TurneroDAO turneroDAO;
    private GestionesDAO gestionesDAO;
    private ModeloAtencionDiferenciadaDAO modeloAtencionDAO;
    private RegistrarAtencionDAO registrarAtencionDAO;
    private List<Turnero> turnosActuales;
    private Integer idBoxActual;

    /**
     * Creates new form frmRegistrarAtencion
     */
    public frmRegistrarAtencion() {
        initComponents();
        
        // Inicializar DAOs
        boxAtencionDAO = new BoxAtencionDAO();
        turneroDAO = new TurneroDAO();
        gestionesDAO = new GestionesDAO();
        modeloAtencionDAO = new ModeloAtencionDiferenciadaDAO();
        registrarAtencionDAO = new RegistrarAtencionDAO();
        
        // Cargar colaboradores
        cargarColaboradores();
        
        // Cargar gestiones
        cargarGestiones();
        
        // Inicializar tabla
        inicializarTabla();
        
        // Deshabilitar botón registrar hasta seleccionar un turno
        btnRegistrarAtencion.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbColaboradores = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaTurnos = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        cmbGestiones = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtObservaciones = new javax.swing.JTextArea();
        btnRegistrarAtencion = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registrar Atención");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Registrar Atención");

        jLabel2.setText("Colaborador:");

        cmbColaboradores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbColaboradoresActionPerformed(evt);
            }
        });

        tablaTurnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código Turno", "Cliente", "Orden", "Prioridad", "Segmento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaTurnos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablaTurnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaTurnosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaTurnos);

        jLabel3.setText("Gestión:");

        jLabel4.setText("Observaciones:");

        txtObservaciones.setColumns(20);
        txtObservaciones.setRows(5);
        jScrollPane2.setViewportView(txtObservaciones);

        btnRegistrarAtencion.setText("Registrar Atención");
        btnRegistrarAtencion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarAtencionActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(cmbColaboradores, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(cmbGestiones, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRegistrarAtencion)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbColaboradores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbGestiones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrarAtencion)
                    .addComponent(btnCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbColaboradoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbColaboradoresActionPerformed
        cargarTurnosDelColaborador();
    }//GEN-LAST:event_cmbColaboradoresActionPerformed

    private void tablaTurnosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaTurnosMouseClicked
        // Habilitar botón cuando se selecciona un turno
        if (tablaTurnos.getSelectedRow() >= 0) {
            btnRegistrarAtencion.setEnabled(true);
        }
    }//GEN-LAST:event_tablaTurnosMouseClicked

    private void btnRegistrarAtencionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarAtencionActionPerformed
        registrarAtencion();
    }//GEN-LAST:event_btnRegistrarAtencionActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * Carga los colaboradores asignados a boxes en el combo
     */
    private void cargarColaboradores() {
        cmbColaboradores.removeAllItems();
        cmbColaboradores.addItem("Seleccione un colaborador...");
        
        List<BoxAtencionDAO.ColaboradorInfo> colaboradores = boxAtencionDAO.listarColaboradoresAsignados();
        
        for (BoxAtencionDAO.ColaboradorInfo colab : colaboradores) {
            cmbColaboradores.addItem(colab);
        }
    }
    
    /**
     * Carga los turnos del colaborador seleccionado
     */
    private void cargarTurnosDelColaborador() {
        if (cmbColaboradores.getSelectedIndex() <= 0) {
            limpiarTabla();
            return;
        }
        
        BoxAtencionDAO.ColaboradorInfo colabInfo = (BoxAtencionDAO.ColaboradorInfo) cmbColaboradores.getSelectedItem();
        if (colabInfo == null) {
            return;
        }
        
        // Obtener el idBox del colaborador
        java.util.Optional<Integer> idBoxOpt = boxAtencionDAO.obtenerIdBoxPorLegajo(colabInfo.legajo);
        if (!idBoxOpt.isPresent()) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "No se encontró un box asignado para este colaborador", 
                "Error", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        idBoxActual = idBoxOpt.get();
        
        // Obtener turnos del box (solo EN_ESPERA)
        turnosActuales = turneroDAO.listarTurnosEnEsperaPorBox(idBoxActual);
        
        // Cargar en la tabla
        cargarTablaTurnos();
    }
    
    /**
     * Carga los turnos en la tabla
     */
    private void cargarTablaTurnos() {
        DefaultTableModel model = (DefaultTableModel) tablaTurnos.getModel();
        model.setRowCount(0);
        
        for (Turnero turno : turnosActuales) {
            Cliente cliente = turno.getCliente();
            
            // Construir nombre completo: "Nombre Apellido"
            String nombreCliente = "N/A";
            if (cliente != null) {
                String nombre = cliente.getNombre() != null ? cliente.getNombre().trim() : "";
                String apellido = cliente.getApellido() != null ? cliente.getApellido().trim() : "";
                if (!nombre.isEmpty() && !apellido.isEmpty()) {
                    nombreCliente = nombre + " " + apellido;
                } else if (!nombre.isEmpty()) {
                    nombreCliente = nombre;
                } else if (!apellido.isEmpty()) {
                    nombreCliente = apellido;
                }
            }
            
            // Obtener segmento del cliente usando idCliente (PK)
            String segmento = "N/A";
            if (cliente != null && cliente.getIdCliente() != null) {
                // El método obtenerSegmentoPorDni busca por idCliente en la BD (aunque el parámetro se llame dni)
                segmento = modeloAtencionDAO.obtenerSegmentoPorDni(cliente.getIdCliente())
                    .orElse("N/A");
            }
            
            model.addRow(new Object[]{
                turno.getCodigoTurno(),
                nombreCliente,
                turno.getOrden() != null ? turno.getOrden() : "N/A",
                turno.getPrioridad() != null ? turno.getPrioridad() : "N/A",
                segmento
            });
        }
    }
    
    /**
     * Limpia la tabla de turnos
     */
    private void limpiarTabla() {
        DefaultTableModel model = (DefaultTableModel) tablaTurnos.getModel();
        model.setRowCount(0);
        btnRegistrarAtencion.setEnabled(false);
    }
    
    /**
     * Carga las gestiones en el combo
     * Muestra solo el nombreGestion pero mantiene el objeto Gestiones para obtener el idGestion
     */
    private void cargarGestiones() {
        cmbGestiones.removeAllItems();
        cmbGestiones.addItem("Seleccione una gestión...");
        
        List<Gestiones> gestiones = gestionesDAO.listarTodas();
        
        System.out.println("=== CARGANDO GESTIONES EN COMBO ===");
        System.out.println("Total de gestiones obtenidas del DAO: " + gestiones.size());
        
        // Crear un renderer personalizado para mostrar solo nombreGestion
        cmbGestiones.setRenderer(new javax.swing.DefaultListCellRenderer() {
            @Override
            public java.awt.Component getListCellRendererComponent(
                    javax.swing.JList<?> list,
                    Object value,
                    int index,
                    boolean isSelected,
                    boolean cellHasFocus) {
                super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                
                if (value instanceof Gestiones) {
                    Gestiones gestion = (Gestiones) value;
                    setText(gestion.getNombreGestion());
                } else if (value != null) {
                    setText(value.toString());
                }
                
                return this;
            }
        });
        
        int itemsAgregados = 0;
        for (Gestiones gestion : gestiones) {
            cmbGestiones.addItem(gestion);
            itemsAgregados++;
            System.out.println("  Agregado al combo: " + gestion.getNombreGestion());
        }
        
        System.out.println("Total de items agregados al combo: " + itemsAgregados);
        System.out.println("Total de items en el combo: " + cmbGestiones.getItemCount());
    }
    
    /**
     * Inicializa la tabla de turnos
     */
    private void inicializarTabla() {
        DefaultTableModel model = (DefaultTableModel) tablaTurnos.getModel();
        model.setRowCount(0);
    }
    
    /**
     * Registra la atención
     */
    private void registrarAtencion() {
        // Validaciones
        if (cmbColaboradores.getSelectedIndex() <= 0) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Debe seleccionar un colaborador", 
                "Error", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (tablaTurnos.getSelectedRow() < 0) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Debe seleccionar un turno", 
                "Error", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (cmbGestiones.getSelectedIndex() <= 0) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Debe seleccionar una gestión", 
                "Error", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Obtener turno seleccionado
        int filaSeleccionada = tablaTurnos.getSelectedRow();
        Turnero turnoSeleccionado = turnosActuales.get(filaSeleccionada);
        
        // Obtener colaborador seleccionado
        BoxAtencionDAO.ColaboradorInfo colabInfo = 
            (BoxAtencionDAO.ColaboradorInfo) cmbColaboradores.getSelectedItem();
        
        // Obtener gestión seleccionada
        Gestiones gestion = (Gestiones) cmbGestiones.getSelectedItem();
        
        // Obtener observaciones
        String observaciones = txtObservaciones.getText().trim();
        
        // Crear registro de atención
        RegistrarAtencion registro = new RegistrarAtencion();
        registro.setFecha(LocalDate.now());
        registro.setCliente(turnoSeleccionado.getCliente());
        // Canal: idCanal = 1 corresponde a "Sucursal"
        modelo.Canal canal = new modelo.Canal(1, "Sucursal");
        registro.setCanal(canal);
        // Obtener modelo usando idCliente (PK)
        if (turnoSeleccionado.getCliente() != null && turnoSeleccionado.getCliente().getIdCliente() != null) {
            // Nota: buscarPorDni usa idCliente en la BD aunque el parámetro se llame dni
            registro.setSegmento(modeloAtencionDAO.buscarPorDni(
                turnoSeleccionado.getCliente().getIdCliente()).orElse(new modelo.ModeloAtencionDiferenciada()));
        } else {
            registro.setSegmento(new modelo.ModeloAtencionDiferenciada());
        }
        
        Colaborador colaborador = new Colaborador();
        colaborador.setLegajo(colabInfo.legajo);
        colaborador.setNombre(colabInfo.nombre);
        colaborador.setApellido(colabInfo.apellido);
        registro.setLegajo(colaborador);
        
        registro.setObservaciones(observaciones.isEmpty() ? null : observaciones);
        registro.setGestiones(gestion);
        
        // Persistir registro de atención
        boolean guardado = registrarAtencionDAO.guardarRegistrarAtencion(registro);
        
        if (guardado) {
            // Actualizar estado del turno a ATENDIDO
            boolean estadoActualizado = turneroDAO.actualizarEstado(
                turnoSeleccionado.getCodigoTurno(), "ATENDIDO");
            
            if (estadoActualizado) {
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "Atención registrada exitosamente", 
                    "Éxito", 
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
                
                // Recargar turnos
                cargarTurnosDelColaborador();
                
                // Limpiar campos
                txtObservaciones.setText("");
                cmbGestiones.setSelectedIndex(0);
                btnRegistrarAtencion.setEnabled(false);
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "Atención registrada pero no se pudo actualizar el estado del turno", 
                    "Advertencia", 
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Error al registrar la atención", 
                "Error", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRegistrarAtencion;
    private javax.swing.JComboBox<Object> cmbColaboradores;
    private javax.swing.JComboBox<Object> cmbGestiones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaTurnos;
    private javax.swing.JTextArea txtObservaciones;
    // End of variables declaration//GEN-END:variables
}
